import { math, text, type QuestionBankItem } from "./types.ts";

const original = {
  kind: "excelora-original" as const,
  authoringVersion: "chapter-1-form-a-v1",
};

// Assessment items live separately from lesson examples and practice questions.
// This is the first release form backed by the reusable question-bank schema.
export const CHAPTER_ONE_ASSESSMENT_FORM_A: QuestionBankItem[] = [
  {
    id: "c1-indices-001",
    number: 1,
    marks: 2,
    topic: "1.1 Laws of Indices",
    skills: ["rewrite-with-a-common-base", "solve-exponential-equation"],
    paragraphs: [[text("Solve "), math(String.raw`8^{x+1}=4^{2x-1}`), text(".")]],
    provenance: original,
  },
  {
    id: "c1-surds-001",
    number: 2,
    marks: 5,
    topic: "1.2 Surds and Rationalising Denominators",
    skills: ["simplify-surds", "expand-surds", "rationalise-denominator"],
    answerParts: [
      { key: "q2_a_i", label: "(a)(i)" },
      { key: "q2_a_ii", label: "(a)(ii)" },
      { key: "q2_b", label: "(b)" },
    ],
    paragraphs: [
      [text("(a) Simplify fully.")],
      [text("(i) "), math(String.raw`\sqrt{75}-\sqrt{12}`)],
      [text("(ii) "), math(String.raw`(2+\sqrt3)(4-3\sqrt3)`) ],
      [text("(b) Rationalise the denominator of "), math(String.raw`\frac5{2+\sqrt3}`), text(" and simplify your answer.")],
    ],
    provenance: original,
  },
  {
    id: "c1-quadratics-001",
    number: 3,
    marks: 2,
    topic: "1.3 Quadratic Functions",
    skills: ["factorise-quadratic"],
    paragraphs: [[text("Factorise fully "), math(String.raw`6x^2+x-2`), text(".")]],
    provenance: original,
  },
  {
    id: "c1-quadratics-002",
    number: 4,
    marks: 3,
    topic: "1.3 Quadratic Functions",
    skills: ["expand-brackets", "solve-quadratic-equation"],
    paragraphs: [[text("Solve "), math(String.raw`(3x-1)^2-(x+2)^2=-3`), text(".")]],
    provenance: original,
  },
  {
    id: "c1-simultaneous-001",
    number: 5,
    marks: 4,
    topic: "1.4 Simultaneous Equations",
    skills: ["linear-quadratic-simultaneous-equations"],
    paragraphs: [[text("Solve simultaneously "), math(String.raw`y=x+1`), text(" and "), math(String.raw`y=x^2-3x+1`), text(". Give both points of intersection.")]],
    provenance: original,
  },
  {
    id: "c1-inequalities-001",
    number: 6,
    marks: 5,
    topic: "1.5 Inequalities",
    skills: ["quadratic-inequality", "rational-inequality"],
    answerParts: [
      { key: "q6_a", label: "(a)" },
      { key: "q6_b", label: "(b)" },
    ],
    paragraphs: [
      [text("Solve each inequality.")],
      [text("(a) "), math(String.raw`3x^2-5x-2\le0`)],
      [text("(b) "), math(String.raw`\frac4{x-1}>2`) ],
    ],
    provenance: original,
  },
  {
    id: "c1-simultaneous-002",
    number: 7,
    marks: 3,
    topic: "1.4 Simultaneous Equations",
    skills: ["discriminant", "line-curve-tangency"],
    answerParts: [
      { key: "q7_a", label: "(a)" },
      { key: "q7_b", label: "(b)" },
    ],
    paragraphs: [
      [text("The line "), math(String.raw`y=3x+c`), text(" is tangent to the curve "), math(String.raw`y=x^2-x+9`), text(".")],
      [text("(a) Find the value of "), math("c"), text(".")],
      [text("(b) Find the coordinates of the point of contact.")],
    ],
    provenance: original,
  },
  {
    id: "c1-modulus-001",
    number: 8,
    marks: 3,
    topic: "1.8 The Modulus Function",
    skills: ["solve-modulus-inequality"],
    paragraphs: [[text("Solve "), math(String.raw`15-3|2x+1|\ge6`), text(".")]],
    provenance: original,
  },
  {
    id: "c1-graphs-001",
    number: 9,
    marks: 5,
    topic: "1.7 Graphs of Functions",
    skills: ["polynomial-intercepts", "polynomial-sign"],
    answerParts: [
      { key: "q9_a", label: "(a)" },
      { key: "q9_b", label: "(b)" },
    ],
    paragraphs: [
      [text("The function "), math(String.raw`f(x)=x(x-3)(x+2)`), text(".")],
      [text("(a) State the coordinates of all the points where its graph meets the "), math("x"), text("-axis.")],
      [text("(b) Hence solve "), math(String.raw`f(x)<0`), text(".")],
    ],
    provenance: original,
  },
  {
    id: "c1-polynomials-001",
    number: 10,
    marks: 7,
    topic: "1.6 Polynomials and Algebraic Division",
    skills: ["remainder-theorem", "polynomial-division"],
    answerParts: [
      { key: "q10_a", label: "(a)" },
      { key: "q10_b", label: "(b)" },
    ],
    paragraphs: [
      [text("A polynomial "), math("f(x)"), text(" gives remainder 7 when divided by "), math("x-1"), text(" and remainder −5 when divided by "), math("x+2"), text(".")],
      [text("(a) When "), math("f(x)"), text(" is divided by "), math(String.raw`(x-1)(x+2)`), text(", the remainder is "), math("ax+b"), text(". Find "), math("a"), text(" and "), math("b"), text(".")],
      [text("(b) Given that "), math(String.raw`f(x)=2x^4+px+q`), text(", express "), math("f(x)"), text(" in the form "), math(String.raw`(x^2+x-2)g(x)+ax+b`), text(" and find "), math("g(x),p"), text(" and "), math("q"), text(".")],
    ],
    provenance: original,
  },
  {
    id: "c1-partial-fractions-001",
    number: 11,
    marks: 8,
    topic: "1.11 Partial Fractions",
    skills: ["partial-fractions", "improper-algebraic-fraction"],
    answerParts: [
      { key: "q11_a", label: "(a)" },
      { key: "q11_b", label: "(b)" },
    ],
    paragraphs: [
      [text("(a) Express "), math(String.raw`\frac{7x+5}{(x+1)(x+3)}`), text(" in partial fractions.")],
      [text("(b) Express "), math(String.raw`\frac{2x^2+3x+4}{x+1}`), text(" in the form "), math(String.raw`ax+b+\frac c{x+1}`), text(".")],
    ],
    provenance: original,
  },
  {
    id: "c1-functions-001",
    number: 12,
    marks: 10,
    topic: "1.9 Composite and Inverse Functions",
    skills: ["composite-functions", "inverse-functions", "domain-and-range"],
    answerParts: [
      { key: "q12_a", label: "(a)" },
      { key: "q12_b", label: "(b)" },
      { key: "q12_c", label: "(c)" },
      { key: "q12_d", label: "(d)" },
      { key: "q12_e", label: "(e)" },
    ],
    paragraphs: [
      [text("The functions "), math(String.raw`f(x)=2x-3`), text(" and "), math(String.raw`g(x)=x^2+1`), text(" are defined for real "), math("x"), text(".")],
      [text("(a) Find "), math("fg(2)"), text(".")],
      [text("(b) Find "), math("gf(x)"), text(" in simplified form.")],
      [text("(c) Find "), math(String.raw`f^{-1}(x)`), text(".")],
      [text("The function "), math(String.raw`h(x)=(x-4)^2+2`), text(" has domain "), math(String.raw`x\ge4`), text(".")],
      [text("(d) Find "), math(String.raw`h^{-1}(x)`), text(", stating its domain.")],
      [text("(e) State the range of "), math("gf(x)"), text(".")],
    ],
    provenance: original,
  },
  {
    id: "c1-transformations-001",
    number: 13,
    marks: 4,
    topic: "1.10 Transformations of Graphs",
    skills: ["translations", "stretches-and-reflections"],
    answerParts: [
      { key: "q13_a", label: "(a)" },
      { key: "q13_b", label: "(b)" },
    ],
    paragraphs: [
      [text("Let "), math(String.raw`f(x)=x^2+2x`), text(".")],
      [text("(a) The graph of "), math("g"), text(" is obtained by translating the graph of "), math("f"), text(" 3 units to the right and 2 units upwards. Find "), math("g(x)"), text(" in simplified form.")],
      [text("(b) Given that "), math(String.raw`h(x)=-2f\left(\frac x2\right)`), text(", find "), math("h(x)"), text(" in simplified form.")],
    ],
    provenance: original,
  },
  {
    id: "c1-modelling-001",
    number: 14,
    marks: 6,
    topic: "1.12 Functions in Modelling",
    skills: ["linear-model", "interpret-gradient", "use-model"],
    answerParts: [
      { key: "q14_a", label: "(a)" },
      { key: "q14_b", label: "(b)" },
      { key: "q14_c", label: "(c)" },
      { key: "q14_d", label: "(d)" },
    ],
    paragraphs: [
      [text("A taxi company models the fare £"), math("C"), text(" for a journey of "), math("d"), text(" kilometres using a linear model. A 6 km journey costs £19 and a 14 km journey costs £35.")],
      [text("(a) Write down the general form of a linear model connecting "), math("C"), text(" and "), math("d"), text(".")],
      [text("(b) Find the model for "), math("C"), text(" in terms of "), math("d"), text(".")],
      [text("(c) Interpret the gradient of your model in context.")],
      [text("(d) Find the greatest whole number of kilometres that can be travelled for £50.")],
    ],
    provenance: original,
  },
  {
    id: "c1-polynomials-002",
    number: 15,
    marks: 8,
    topic: "1.6 Polynomials and Algebraic Division",
    skills: ["factor-theorem", "factorise-cubic", "polynomial-inequality"],
    answerParts: [
      { key: "q15_a", label: "(a)" },
      { key: "q15_b", label: "(b)" },
      { key: "q15_c", label: "(c)" },
      { key: "q15_d", label: "(d)" },
    ],
    paragraphs: [
      [text("The function "), math(String.raw`f(x)=x^3-4x^2-x+4`), text(".")],
      [text("(a) Show that "), math("x-1"), text(" is a factor of "), math("f(x)"), text(".")],
      [text("(b) Factorise "), math("f(x)"), text(" completely.")],
      [text("(c) Solve "), math("f(x)=0"), text(".")],
      [text("(d) Hence solve "), math("f(x)>0"), text(".")],
    ],
    provenance: original,
  },
];
