import { nativeLesson, p, m, h, group, example, step, table } from './authoring.ts';
const lesson=(source:string,blocks:Parameters<typeof nativeLesson>[3])=>nativeLesson('Pure Mathematics','Chapter 2: Proof',source,blocks);
const raw=String.raw;
export const PROOF_LESSONS=[
lesson('2.2 Proof by Deduction',[
 p('Proof by deduction is the standard method of mathematical proof. You start with definitions, axioms, or previously established results and apply logical reasoning to arrive at the desired conclusion. Algebraic manipulation, completing the square, and differentiation from first principles are all examples of deductive proof.'),
 group('Common Deductive Strategies',[
 p('Direct algebraic manipulation: Rearrange one side of an identity to equal the other.'),
 p('Completing the square: Write $ax^2+bx+c$ as $a(x+p)^2+q$ to establish positivity or find minimum values.'),
 p('Using known results: Apply established identities (e.g. trigonometric, index laws) to derive new ones.'),
 p('Working from definitions: Use the definition of the derivative, for example, to prove differentiation rules from first principles.'),
 ]),h('Worked Examples'),
 example([p('Prove that $n^2-6n+10$ is positive for all values of $n$.'),p('Complete the square:'),m(raw`\begin{aligned}n^2-6n+10&=(n-3)^2-9+10\\&=(n-3)^2+1\end{aligned}`),p(raw`Since $(n-3)^2\ge0$ for all real $n$, it follows that $(n-3)^2+1\ge1$. Therefore $n^2-6n+10\ge1>0$ for all values of $n$.`)]),
 example([p('Show that $k^2-4k+5$ is positive for all real values of $k$.'),p('Complete the square:'),m(raw`\begin{aligned}k^2-4k+5&=(k-2)^2-4+5\\&=(k-2)^2+1\end{aligned}`),p(raw`Since $(k-2)^2\ge0$ for all real $k$, we have $(k-2)^2+1\ge1>0$.`),p('Therefore $k^2-4k+5$ is positive for all real values of $k$.')]),
 example([p('Prove that the sum of two consecutive odd numbers is divisible by 4.'),step(1,'Write two consecutive odd numbers algebraically.',[p('Let the first odd number be $2n-1$ where $n$ is a positive integer. The next consecutive odd number is $2n+1$.')]),step(2,'Find their sum:',[m('(2n-1)+(2n+1)=4n')]),step(3,'Conclude.',[p(raw`Since $4n=4\times n$ and $n$ is an integer, $4n$ is divisible by 4.`),p('Therefore the sum of any two consecutive odd numbers is divisible by 4.')])]),
 example([p('Prove that the product of two consecutive even numbers is divisible by 8.'),p('Let the two consecutive even numbers be $2n$ and $2n+2$, where $n$ is a positive integer.'),p('Their product is:'),m(raw`2n(2n+2)=2n\cdot2(n+1)=4n(n+1)`),p('Now, $n$ and $n+1$ are consecutive integers, so one of them must be even. Therefore $n(n+1)$ is even, meaning $n(n+1)=2m$ for some integer $m$.'),p(raw`Substituting: $4n(n+1)=4\cdot2m=8m$.`),p('Since $8m$ is divisible by 8, the product of any two consecutive even numbers is divisible by 8.')]),
 group('Practice Questions',[
 p('1. Prove that $(3n+1)^2-(3n-1)^2$ is divisible by 12 for all positive integers $n$.'),p('2. Prove that $2x^2+8x+9>0$ for all real values of $x$.'),p('3. Prove that the difference between the squares of any two consecutive integers is odd.'),p(raw`4. Prove that for all real numbers $a$ and $b$, $a^2+b^2\ge2ab$.`),
 ]),group('Solutions to Practice Questions',[
 example([p('1. Prove that $(3n+1)^2-(3n-1)^2$ is divisible by 12 for all positive integers $n$.'),p('Expand using the difference of two squares:'),m(raw`\begin{aligned}(3n+1)^2-(3n-1)^2&=[(3n+1)+(3n-1)]\\&\quad\cdot[(3n+1)-(3n-1)]\\&=(6n)(2)\\&=12n\end{aligned}`),p(raw`Since $12n=12\times n$ and $n$ is a positive integer, $12n$ is divisible by 12.`)]),
 example([p('2. Prove that $2x^2+8x+9>0$ for all real values of $x$.'),p('Complete the square:'),m(raw`\begin{aligned}2x^2+8x+9&=2(x^2+4x)+9\\&=2[(x+2)^2-4]+9\\&=2(x+2)^2-8+9\\&=2(x+2)^2+1\end{aligned}`),p(raw`Since $(x+2)^2\ge0$ for all $x$, we have $2(x+2)^2+1\ge1>0$.`),p('Therefore $2x^2+8x+9>0$ for all real values of $x$.')]),
 example([p('3. Prove that the difference between the squares of any two consecutive integers is odd.'),p('Let the two consecutive integers be $n$ and $n+1$.'),m('(n+1)^2-n^2=n^2+2n+1-n^2=2n+1'),p('Since $2n$ is even, $2n+1$ is odd. Therefore the difference between the squares of any two consecutive integers is always odd.')]),
 example([p(raw`4. Prove that for all real numbers $a$ and $b$, $a^2+b^2\ge2ab$.`),p('Rearrange:'),m('a^2+b^2-2ab=(a-b)^2'),p(raw`Since $(a-b)^2\ge0$ for all real $a$ and $b$, it follows that $a^2+b^2-2ab\ge0$, i.e. $a^2+b^2\ge2ab$.`)]),
 ]),
]),
lesson('2.3 Proof by Exhaustion',[
 p('Proof by exhaustion verifies a statement by checking every possible case. This method is only practical when the number of cases is finite and manageable. The key is to partition the possibilities into a complete, non-overlapping set of cases and verify the statement holds in each one.'),
 group('Proof by Exhaustion — Method',[p('Step 1: Identify all possible cases that cover the full range of the statement.'),p('Step 2: Verify the statement holds in each case individually.'),p('Step 3: Conclude that since the statement is true in every case, it is true in general.'),p('Common partitions: even/odd, positive/negative/zero, modular arithmetic residues ($n=3k,3k+1,3k+2$).')]),
 h('Worked Examples'),example([
 p('Given that $p$ is a prime number such that $3<p<25$, prove by exhaustion that $(p-1)(p+1)$ is a multiple of 12.'),p('Step 1: List all primes with $3<p<25$: $p=5,7,11,13,17,19,23$.'),p('Step 2: Compute $(p-1)(p+1)=p^2-1$ for each:'),
 table(['$p$','$p^2-1$','Divisible by 12?'],[['$5$','$24$',raw`$24=12\times2$ Yes`],['$7$','$48$',raw`$48=12\times4$ Yes`],['$11$','$120$',raw`$120=12\times10$ Yes`],['$13$','$168$',raw`$168=12\times14$ Yes`],['$17$','$288$',raw`$288=12\times24$ Yes`],['$19$','$360$',raw`$360=12\times30$ Yes`],['$23$','$528$',raw`$528=12\times44$ Yes`]]),p('Step 3: Since $(p-1)(p+1)$ is a multiple of 12 for every prime $p$ with $3<p<25$, the statement is proved by exhaustion.'),
 ]),example([
 p(raw`Prove by exhaustion that the square of any positive integer $n$ can never be of the form $3k+2$ where $k\in\mathbb{N}$.`),p('Step 1: Every positive integer takes one of three forms when divided by 3: $n=3m$, $n=3m+1$, or $n=3m+2$ for some non-negative integer $m$.'),p('Step 2 — Case 1: $n=3m$.'),m('n^2=9m^2=3(3m^2)'),p('This is of the form $3k$ (i.e. remainder 0 when divided by 3).'),p('Case 2: $n=3m+1$.'),m('n^2=9m^2+6m+1=3(3m^2+2m)+1'),p('This is of the form $3k+1$.'),p('Case 3: $n=3m+2$.'),m('n^2=9m^2+12m+4=3(3m^2+4m+1)+1'),p('This is also of the form $3k+1$.'),p('Step 3: In all three cases, $n^2$ is either of the form $3k$ or $3k+1$. It is never of the form $3k+2$. Since every positive integer falls into one of these three cases, the proof is complete.'),
 ]),group('Practice Questions',[p('1. Prove by exhaustion that $n^2+2$ is not divisible by 4 for all positive integers $n$.'),p(raw`2. Prove by exhaustion that for all integers $n$ with $1\le n\le6$, $n^3+11n$ is divisible by 6.`),p('3. Prove by exhaustion that $n^2+n$ is even for all positive integers $n$.')]),
 group('Solutions to Practice Questions',[
 example([p('1. Prove by exhaustion that $n^2+2$ is not divisible by 4 for all positive integers $n$.'),p('Every positive integer is either even or odd.'),p('Case 1: $n=2m$ (even).'),m('n^2+2=4m^2+2'),p('Since $4m^2$ is divisible by 4 but $4m^2+2$ leaves remainder 2 when divided by 4, this is not divisible by 4.'),p('Case 2: $n=2m+1$ (odd).'),m(raw`\begin{aligned}n^2+2&=4m^2+4m+1+2\\&=4m^2+4m+3\\&=4m(m+1)+3\end{aligned}`),p('Since $4m(m+1)$ is divisible by 4, the expression $4m(m+1)+3$ leaves remainder 3 when divided by 4, so it is not divisible by 4.'),p('In both cases, $n^2+2$ is not divisible by 4.')]),
 example([p(raw`2. Prove by exhaustion that for all integers $n$ with $1\le n\le6$, $n^3+11n$ is divisible by 6.`),table(['$n$','$n^3+11n$','Divisible by 6?'],[['$1$','$1+11=12$',raw`$12=6\times2$ Yes`],['$2$','$8+22=30$',raw`$30=6\times5$ Yes`],['$3$','$27+33=60$',raw`$60=6\times10$ Yes`],['$4$','$64+44=108$',raw`$108=6\times18$ Yes`],['$5$','$125+55=180$',raw`$180=6\times30$ Yes`],['$6$','$216+66=282$',raw`$282=6\times47$ Yes`]]),p(raw`Since $n^3+11n$ is divisible by 6 in every case, the statement is proved by exhaustion for $1\le n\le6$.`)]),
 example([p('3. Prove by exhaustion that $n^2+n$ is even for all positive integers $n$.'),p('Case 1: $n$ is even, say $n=2m$.'),m('n^2+n=4m^2+2m=2(2m^2+m)'),p('This is even.'),p('Case 2: $n$ is odd, say $n=2m+1$.'),m(raw`\begin{aligned}n^2+n&=(2m+1)^2+(2m+1)\\&=4m^2+4m+1+2m+1\\&=4m^2+6m+2\\&=2(2m^2+3m+1)\end{aligned}`),p('This is even.'),p('In both cases $n^2+n$ is even, so the result holds for all positive integers $n$.')]),
 ]),
]),
lesson('2.4 Disproof by Counter Example',[
 p('To disprove a statement of the form “for all $x$, …”, it is sufficient to find a single value of $x$ for which the statement fails. This single example is called a counter example. It does not matter how many cases satisfy the statement; one failure is enough to disprove it.'),
 group('Disproof by Counter Example — Method',[p('Step 1: Identify the claim being made (usually a “for all” statement).'),p('Step 2: Find one specific value that makes the statement false.'),p('Step 3: Verify by substitution that the statement fails for that value.'),p('Step 4: Conclude that the statement is false.')]),
 h('Worked Examples'),example([p('Disprove the statement: “$n^2-n+1$ is a prime number for all positive integer values of $n$.”'),p('Test values of $n$:'),p('$n=1$: $1-1+1=1$ (not prime, but not explicitly claimed to be — let us continue).'),p('$n=2$: $4-2+1=3$ (prime).'),p('$n=3$: $9-3+1=7$ (prime).'),p('$n=4$: $16-4+1=13$ (prime).'),p(raw`$n=5$: $25-5+1=21=3\times7$ (not prime).`),p('Since $n=5$ gives $n^2-n+1=21$, which is not prime, the statement is disproved.')]),
 example([p('Disprove the statement: “If $a>b$, then $a^2>b^2$.”'),p('Consider $a=1$ and $b=-3$.'),p('Then $a>b$ since $1>-3$. But $a^2=1$ and $b^2=9$, so $a^2<b^2$.'),p('This is a counter example, so the statement is false.')]),
 example([p(raw`“Given $x\in\mathbb{R}$, the value of $|3x-28|$ is greater than or equal to $(x-9)$.” Determine whether this statement is always true, sometimes true, or never true.`),p(raw`Step 1: Test a few values. When $x=0$: $|-28|=28\ge-9$. True.`),p(raw`When $x=10$: $|2|=2$ and $x-9=1$. $2\ge1$. True.`),p(raw`Step 2: Consider when the statement might fail. We need $|3x-28|<x-9$, which requires $x>9$ (otherwise $x-9\le0$ and the modulus is always non-negative). For $x>28/3\approx9.33$, $|3x-28|=3x-28$.`),p('So we need $3x-28<x-9$, giving $2x<19$, i.e. $x<9.5$.'),p(raw`So the statement fails when $9.33\ldots<x<9.5$. Try $x=9.4$: $|3(9.4)-28|=|0.2|=0.2$ and $9.4-9=0.4$. Since $0.2<0.4$, the statement fails.`),p('The statement is sometimes true.')]),
 group('Practice Questions',[p('1. Disprove: “$2n+1$ is prime for all positive integers $n$.”'),p('2. Disprove: “For all real numbers $x$, $x^2>x$.”'),p('3. Disprove: “If $n$ is a positive integer, then $n^2+n+41$ is always prime.”')]),
 group('Solutions to Practice Questions',[
 example([p('1. Disprove: “$2n+1$ is prime for all positive integers $n$.”'),p(raw`Try $n=4$: $2(4)+1=9=3\times3$, which is not prime.`),p('The statement is disproved by the counter example $n=4$.')]),
 example([p('2. Disprove: “For all real numbers $x$, $x^2>x$.”'),p(raw`Try $x=\frac12$: $x^2=\frac14$ and $x=\frac12$. Since $\frac14<\frac12$, we have $x^2<x$.`),p(raw`The statement is disproved by the counter example $x=\frac12$.`)]),
 example([p('3. Disprove: “If $n$ is a positive integer, then $n^2+n+41$ is always prime.”'),p('Try $n=40$: $40^2+40+41=1600+40+41=1681=41^2$, which is not prime.'),p('The statement is disproved by the counter example $n=40$.')]),
 ]),
]),
lesson('2.5 Proof by Contradiction',[
 p('In a proof by contradiction, we assume the negation of the statement we wish to prove and then show that this assumption leads to a logical impossibility (a contradiction). Since the assumption produces a contradiction, it must be false, so the original statement must be true.'),
 group('Proof by Contradiction — Method',[p('Step 1: State the assumption — assume the opposite of what you wish to prove.'),p('Step 2: Use logical deduction from this assumption.'),p('Step 3: Arrive at a contradiction — a statement that is impossible or conflicts with a known fact.'),p('Step 4: Conclude that the original assumption was false, and therefore the original statement is true.')]),h('Worked Examples'),
 example([p(raw`Prove by contradiction that $\sqrt2$ is irrational.`),p(raw`Step 1 — Assumption: Assume, for the sake of contradiction, that $\sqrt2$ is rational. Then $\sqrt2=\frac{a}{b}$ where $a,b$ are positive integers with no common factor (i.e. the fraction is in its simplest form).`),p('Step 2: Square both sides:'),m(raw`2=\frac{a^2}{b^2}\implies a^2=2b^2`),p('This means $a^2$ is even. Since the square of an odd number is odd, $a$ itself must be even. Write $a=2k$ for some positive integer $k$.'),p('Step 3: Substitute $a=2k$:'),m(raw`\begin{aligned}(2k)^2&=2b^2\\4k^2&=2b^2\\b^2&=2k^2\end{aligned}`),p('This means $b^2$ is even, so $b$ is also even.'),p(raw`Step 4 — Contradiction: Both $a$ and $b$ are even, so they share a common factor of 2. This contradicts our assumption that $\frac{a}{b}$ was in its simplest form.`),p(raw`Therefore our assumption is false, and $\sqrt2$ is irrational.`)]),
 example([p('Prove by contradiction that there are infinitely many prime numbers.'),p(raw`Step 1 — Assumption: Assume, for the sake of contradiction, that there are finitely many primes. List them all as $p_1,p_2,p_3,\ldots,p_n$.`),p('Step 2: Construct the number:'),m(raw`N=p_1\times p_2\times p_3\times\cdots\times p_n+1`),p('Step 3: Consider what happens when we divide $N$ by any prime in our list. For each $p_i$:'),m(raw`N\div p_i=\frac{p_1p_2\cdots p_n}{p_i}+\frac1{p_i}`),p(raw`The first term is an integer, but $\frac1{p_i}$ is not (since each $p_i\ge2$). So $N$ is not divisible by any $p_i$. In other words, $N$ leaves remainder 1 when divided by any prime in the list.`),p('Step 4 — Contradiction: $N>1$, so by the fundamental theorem of arithmetic, $N$ must have a prime factor. But $N$ is not divisible by any prime in our complete list. This is a contradiction.'),p('Therefore there are infinitely many primes.')]),
 example([p('Prove by contradiction that there are no positive integers $x$ and $y$ such that $(3x+2y)(2x-5y)=28$.'),p('Step 1 — Assumption: Assume positive integers $x,y$ exist with $(3x+2y)(2x-5y)=28$.'),p(raw`Step 2: Since $x,y$ are positive integers, $3x+2y\ge3(1)+2(1)=5$. Also $3x+2y$ is a positive integer.`),p(raw`The factor pairs of 28 (where both factors are integers) are: $1\times28$, $2\times14$, $4\times7$, $7\times4$, $14\times2$, $28\times1$. We also need to consider negative factor pairs: $(-1)(-28)$, $(-2)(-14)$, $(-4)(-7)$.`),p(raw`Since $3x+2y\ge5$, the possible cases are:`),p('Case 1: $3x+2y=7$, $2x-5y=4$.'),p(raw`Solving: from the first equation $x=\frac{7-2y}{3}$. Substitute into the second: $\frac{2(7-2y)}3-5y=4$, so $14-4y-15y=12$, giving $19y=2$, $y=\frac2{19}$. Not a positive integer.`),p('Case 2: $3x+2y=14$, $2x-5y=2$.'),p(raw`From the second: $x=\frac{2+5y}{2}$. Substitute: $\frac{3(2+5y)}2+2y=14$, so $6+15y+4y=28$, giving $19y=22$, $y=\frac{22}{19}$. Not a positive integer.`),p('Case 3: $3x+2y=28$, $2x-5y=1$.'),p(raw`From the second: $x=\frac{1+5y}{2}$. Substitute: $\frac{3(1+5y)}2+2y=28$, so $3+15y+4y=56$, giving $19y=53$, $y=\frac{53}{19}$. Not a positive integer.`),p(raw`Cases with $2x-5y$ negative: Since $3x+2y\ge5$, we check $3x+2y=-4,-2,-1$ — but these are impossible since $3x+2y\ge5$.`),p(raw`The remaining pair is $3x+2y=4$, $2x-5y=7$, but $3x+2y\ge5$, so this is impossible.`),p('Step 3 — Contradiction: No factor pair yields positive integer solutions for both $x$ and $y$.'),p('Therefore there are no positive integers $x,y$ satisfying $(3x+2y)(2x-5y)=28$.')]),
 group('Practice Questions',[p('1. Prove by contradiction that if $n^2$ is even, then $n$ is even.'),p(raw`2. Prove by contradiction that $\sqrt3$ is irrational.`),p('3. Prove by contradiction that there is no largest even number.'),p('4. Prove by contradiction that if $a$ and $b$ are real numbers and $a+b$ is irrational, then at least one of $a$ or $b$ is irrational.')]),
 group('Solutions to Practice Questions',[
 example([p('1. Prove by contradiction that if $n^2$ is even, then $n$ is even.'),p('Assumption: Suppose $n^2$ is even but $n$ is odd. Then $n=2k+1$ for some integer $k$.'),m('n^2=(2k+1)^2=4k^2+4k+1=2(2k^2+2k)+1'),p('This is odd. But we assumed $n^2$ is even — a contradiction.'),p('Therefore if $n^2$ is even, $n$ must be even.')]),
 example([p(raw`2. Prove by contradiction that $\sqrt3$ is irrational.`),p(raw`Assumption: Suppose $\sqrt3=\frac{a}{b}$ with $a,b$ positive integers, $\gcd(a,b)=1$.`),p(raw`Squaring: $3=\frac{a^2}{b^2}$, so $a^2=3b^2$.`),p('Then $a^2$ is divisible by 3, so $a$ is divisible by 3 (since if $a$ were not divisible by 3, $a^2$ would leave remainder 1 when divided by 3). Write $a=3m$.'),p('Substituting: $9m^2=3b^2$, so $b^2=3m^2$.'),p(raw`Then $b$ is also divisible by 3. But this contradicts $\gcd(a,b)=1$.`),p(raw`Therefore $\sqrt3$ is irrational.`)]),
 example([p('3. Prove by contradiction that there is no largest even number.'),p('Assumption: Suppose there is a largest even number $N$.'),p('Consider $N+2$. Since $N$ is even, $N+2$ is also even. And $N+2>N$.'),p('This contradicts the assumption that $N$ is the largest even number.'),p('Therefore there is no largest even number.')]),
 example([p('4. Prove by contradiction that if $a+b$ is irrational, then at least one of $a$ or $b$ is irrational.'),p('Assumption: Suppose $a+b$ is irrational, but both $a$ and $b$ are rational.'),p(raw`If $a$ and $b$ are rational, then $a=\frac{p}{q}$ and $b=\frac{r}{s}$ for integers $p,q,r,s$ with $q,s\ne0$.`),p(raw`Then $a+b=\frac{p}{q}+\frac{r}{s}=\frac{ps+qr}{qs}$, which is a ratio of integers and hence rational.`),p('This contradicts the assumption that $a+b$ is irrational.'),p('Therefore at least one of $a$ or $b$ must be irrational.')]),
 ]),
]),
];
