import {nativeLesson,p,m,h,group,example,table} from './authoring.ts';
import type {LessonBlock} from '../../lib/lessons/schema.ts';
const raw=String.raw;
const lesson=(title:string,blocks:LessonBlock[])=>nativeLesson('Statistics','Chapter 1: Data Collection',title,blocks);
const populationQuestions=[
 [p('1. A school uses a census to investigate the dietary requirements of its 800 students.'),p('(a) Explain what is meant by a census.'),p('(b) Give one advantage and one disadvantage to the school of using a census.')],
 [p('2. A manufacturer of light bulbs wishes to test how long each bulb lasts before failing. They produce 10 000 bulbs per day.'),p('(a) Suggest a reason why a census would not be appropriate.'),p('(b) Identify the sampling units.'),p('(c) Suggest a suitable sampling frame.')],
 [p('3. A city council wants to find out what residents think about a new recycling scheme. There are 45 000 households in the city.'),p('(a) Give one reason why the council should not take a census.'),p('(b) State one advantage of using a sample instead.')],
];
const samplingQuestions=[
 [p('1. A head of sixth form wants to get the opinion of Year 12 and Year 13 students about the facilities in the common room. There are 70 male and 85 female students in Year 12, and 50 male and 75 female students in Year 13.'),p('(a) Suggest a suitable sampling method to take a sample of 40 students.'),p('(b) How many students from each gender in each year should be asked?')],
 [p('2. A gym wants to take a sample of its members. Each member has a 5-digit membership number, and the gym selects every member with a membership number ending 000.'),p('(a) Is this a systematic sample? Give a reason for your answer.'),p('(b) Suggest one way of improving the reliability of this sample.')],
 [p('3. Describe the similarities and differences between quota sampling and stratified random sampling.')],
 [p('4. A researcher is collecting data on the radio-listening habits of people in a local town. She asks the first 5 people she sees on a Monday morning entering a supermarket. The number of hours per week each person listens is: 4, 7, 6, 8, 2.'),p('(a) Use the sample data to work out a prediction for the average number of hours listened per week for the town as a whole.'),p('(b) Describe the sampling method used and comment on the reliability of the data.'),p('(c) Suggest two improvements to the method used.')],
];
const typeQuestions=[
 p('1. State whether each of the following variables is qualitative or quantitative: (a) height of a tree, (b) colour of car, (c) time waiting in a queue, (d) shoe size, (e) names of pupils in a class.'),
 p('2. State whether each of the following quantitative variables is continuous or discrete: (a) shoe size, (b) length of leaf, (c) number of people on a bus, (d) weight of sugar, (e) time required to run 100 m.'),
 p('3. The distribution of the masses of two-month-old lambs is shown in the table.'),
];
const massParts=[p('(a) Write down the class boundaries for the third group.'),p('(b) Work out the midpoint of the second group.'),p('(c) Work out the class width of the first group.')];
const dataQuestions=[
 p('1. State which of the following variables from the large data set are qualitative and which are quantitative: (a) daily mean temperature, (b) daily mean wind direction (compass), (c) daily total rainfall, (d) cloud cover in oktas.'),
 p('2. Explain why the large data set records data for two different time periods (1987 and 2015).'),
 p('3. A student wishes to calculate the standard deviation of daily total sunshine for Leuchars in August 2015. Explain one issue they might encounter with the data and how they should deal with it.'),
 p('4. Name two variables that are recorded for all eight weather stations and two variables that are recorded only for the UK stations.'),
];
export const STATISTICS_COLLECTION_LESSONS=[
lesson('1.1 Populations and Samples',[
 p('In statistics, we begin by understanding the difference between a population and a sample. These concepts underpin every statistical investigation and determine the scope, accuracy and practicality of the conclusions we draw.'),
 group('Key Definitions',[
 p('A population is the whole set of items that are of interest in a statistical investigation.'),p('A census observes or measures every member of a population.'),p('A sample is a selection of observations taken from a subset of the population, used to find out information about the population as a whole.'),p('Individual units of a population are known as sampling units. A list of all sampling units, each individually named or numbered, is called a sampling frame.'),
 ]),p('A census provides complete information about a population, but it is often impractical. The table below compares the advantages and disadvantages of a census and a sample.'),
 table(['','Advantages','Disadvantages'],[
 ['Census','Completely accurate results','Time consuming and expensive; cannot be used if testing destroys items; hard to process large quantities of data'],
 ['Sample','Less time consuming and cheaper; fewer people have to respond; less data to process','May not be as accurate; sample may not represent the population'],
 ]),p('The size of a sample can affect the validity of conclusions drawn. Generally, the larger the sample, the more accurate the results, but at greater cost. If the population is very varied, a larger sample is needed than if the population were uniform.'),
 group('Worked Example 1',[
 p('A supermarket wants to test a delivery of avocados for ripeness by cutting them in half.'),p('(a) Suggest a reason why the supermarket should not test all the avocados in the delivery.'),p('The supermarket tests a sample of 5 avocados and finds that 4 of them are ripe. They estimate that 80% of the avocados in the delivery are ripe.'),p('(b) Suggest one way that the supermarket could improve their estimate.'),p('(a) Testing all the avocados would destroy them (cutting them in half), so there would be none left to sell. A census is not appropriate when the testing process destroys the item.'),p('(b) They could take a larger sample, for example 20 avocados. A larger sample would give a more reliable estimate of the overall proportion of ripe avocados in the delivery.'),
 ]),group('Worked Example 2',[
 p('A factory manager wants to investigate the reliability of components produced on a production line. There are 5000 components produced each day.'),p('(a) Identify the population.'),p('(b) Give one advantage and one disadvantage of using a census to test the components.'),p('(c) Suggest a suitable sampling frame.'),p('(a) The population is all 5000 components produced each day on the production line.'),p('(b) Advantage: A census would give completely accurate information about the reliability of every component.'),p('Disadvantage: Testing every component would be time consuming, expensive and impractical. If the reliability test destroys the component, there would be none left to sell.'),p('(c) A suitable sampling frame would be a numbered list of all 5000 components, for example using serial numbers assigned during production.'),
 ]),group('Practice Questions',populationQuestions.flatMap(q=>[example(q)])),group('Practice Solutions',[
 example([...populationQuestions[0],p('(a) A census is when every member of the population is surveyed or measured. In this case, all 800 students would be asked about their dietary requirements.'),p('(b) Advantage: The school will obtain completely accurate information about the dietary requirements of every student, meaning no student is overlooked.'),p('Disadvantage: It would be time consuming to survey all 800 students and process all the responses. Some students may be absent and missed.')]),
 example([...populationQuestions[1],p('(a) Testing a light bulb until it fails destroys it, so a census would destroy all 10 000 bulbs and leave none to sell. A sample must be used instead.'),p('(b) The sampling units are the individual light bulbs.'),p('(c) A suitable sampling frame would be a numbered list of all 10 000 bulbs, using serial numbers or production-line identifiers assigned to each bulb.')]),
 example([...populationQuestions[2],p('(a) Surveying all 45 000 households would be very time consuming and expensive for the council. It would also be difficult to ensure that every household responds.'),p('(b) A sample would be cheaper and quicker to carry out, allowing the council to gather useful information without the cost of contacting every household.')]),
 ]),
]),
lesson('1.2 Sampling Methods',[
 p('When collecting data, the method used to select a sample is crucial. A well-chosen method produces a representative sample that reflects the population; a poorly chosen method introduces bias. There are three types of random sampling and two types of non-random sampling that you need to know.'),
 h('2.1 Random Sampling'),p('In random sampling, every member of the population has a chance of being selected. This helps to remove bias and produce a representative sample.'),
 group('Simple Random Sampling',[p('A simple random sample of size $n$ is one where every sample of size $n$ has an equal chance of being selected.'),p('Method: Allocate a unique number to every member of the population using a sampling frame. Then use a random number generator (or lottery method) to select $n$ numbers. The corresponding members form the sample.')]),
 group('Systematic Sampling',[p('In systematic sampling, the required elements are chosen at regular intervals from an ordered list.'),p(raw`Method: Calculate the sampling interval $k=\frac{\text{population size}}{\text{sample size}}$. Choose a random starting point from the first $k$ members, then select every $k$th member thereafter.`)]),
 group('Stratified Sampling',[p('In stratified sampling, the population is divided into mutually exclusive strata (groups) and a random sample is taken from each stratum.'),p('The number sampled from each stratum is:'),m(raw`\text{Number from stratum}=\frac{\text{number in stratum}}{\text{total population}}\times\text{overall sample size}`)]),
 p('Each method has advantages and disadvantages. Simple random sampling is free of bias and easy for small populations, but requires a sampling frame and is unsuitable for very large populations. Systematic sampling is simple and quick, but can introduce bias if the list has a periodic pattern. Stratified sampling guarantees proportional representation of subgroups, but requires the population to be clearly classifiable into distinct strata.'),
 group('Worked Example 3',[
 p('A factory manager wants to find out what his 300 workers think about the canteen facilities. He decides to give a questionnaire to a sample of 80 workers. There are 75 workers aged 18–32, 140 workers aged 33–47 and 85 workers aged 48–62. Different age groups are thought to have different opinions.'),p('(a) Write down the name of the method of sampling the manager should use.'),p('(b) Explain how he could use this method to select a sample of workers’ opinions.'),p('(a) Stratified sampling. The population is naturally divided into distinct age groups (strata), and the manager believes opinions differ between groups, so proportional representation is important.'),p('(b) Step 1: Calculate the total number of workers: $75+140+85=300$.'),p('Step 2: Calculate the number to sample from each stratum:'),m(raw`\text{Age 18–32:}\quad\frac{75}{300}\times80=20\text{ workers}`),m(raw`\text{Age 33–47:}\quad\frac{140}{300}\times80=37.3\approx37\text{ workers}`),m(raw`\text{Age 48–62:}\quad\frac{85}{300}\times80=22.6\approx23\text{ workers}`),p('Step 3: Number the workers in each age group. Use a random number generator to select the required quantity from each group. Give the questionnaire to the selected workers.'),
 ]),group('Worked Example 4',[
 p('A factory has 480 workers, each with a clocking-in number from 1 to 480. The manager wants to take a systematic sample of size 30 from these workers.'),p('Explain how the manager could take this sample.'),p('Step 1: Calculate the sampling interval:'),m(raw`k=\frac{480}{30}=16`),p('Step 2: Choose a random starting point. Use a random number generator to select a number between 1 and 16. Suppose the starting number is 5.'),p('Step 3: Select every 16th worker from the starting point. The sample would consist of workers numbered 5, 21, 37, 53, 69, …, and so on, until 30 workers have been selected.'),p(raw`In general, if the random starting point is $r$, the sample consists of workers numbered $r,r+16,r+32,\ldots,r+29\times16$.`),
 ]),h('2.2 Non-Random Sampling'),p('Non-random sampling methods do not give every member of the population a chance of being selected. They are typically quicker and cheaper, but are more susceptible to bias.'),
 group('Quota Sampling',[p('In quota sampling, an interviewer selects a sample that reflects the characteristics of the whole population. The population is divided into groups and a quota is set for each group. The interviewer fills each quota by selecting people who fit the criteria.'),p('Advantages: No sampling frame needed; quick, easy and inexpensive; allows comparison between groups.'),p('Disadvantages: Non-random so can introduce bias; non-responses are not recorded; dependent on the interviewer’s judgement.')]),
 group('Opportunity Sampling',[p('Opportunity sampling (convenience sampling) consists of taking the sample from people who are available at the time and place the study is carried out and who fit the required criteria.'),p('Advantages: Easy to carry out; inexpensive.'),p('Disadvantages: Unlikely to provide a representative sample; highly dependent on the individual researcher.')]),
 group('Worked Example 5',[
 p('An interviewer asks the first 50 people he sees outside a fish and chip shop on a Friday evening about their eating habits.'),p('(a) What type of sampling method did he use?'),p('(b) Explain why the sampling method may not be representative.'),p('(c) Suggest two improvements he could make to his data collection technique.'),p('(a) Opportunity sampling (convenience sampling), because the interviewer selected people who were available at that particular time and place.'),p('(b) The sample is unlikely to be representative because people outside a fish and chip shop on a Friday evening are likely to have different eating habits from the general population. The sample is biased towards people who eat takeaway food, and the time (Friday evening) and location introduce further bias.'),p('(c) Improvement 1: The interviewer could collect data at different locations — for example, outside a supermarket, gym and restaurant — to capture a wider range of eating habits.'),p('Improvement 2: The interviewer could collect data at different times of day and on different days of the week to reduce the effect of time-related bias.'),
 ]),group('Practice Questions',samplingQuestions.map(example)),group('Practice Solutions',[
 example([...samplingQuestions[0],p('(a) Stratified sampling is the most appropriate method, since the population is naturally divided into groups (year and gender), and different groups may have different opinions.'),p('(b) Total number of students: $70+85+50+75=280$.'),p('Calculate the number from each group:'),m(raw`\text{Year 12 Male:}\quad\frac{70}{280}\times40=10`),m(raw`\text{Year 12 Female:}\quad\frac{85}{280}\times40=\frac{340}{28}\approx12.1\approx12`),m(raw`\text{Year 13 Male:}\quad\frac{50}{280}\times40=\frac{200}{28}\approx7.1\approx7`),m(raw`\text{Year 13 Female:}\quad\frac{75}{280}\times40=\frac{300}{28}\approx10.7\approx11`),p('Check: $10+12+7+11=40$. The head of sixth form should ask 10 Year 12 males, 12 Year 12 females, 7 Year 13 males and 11 Year 13 females.')]),
 example([...samplingQuestions[1],p('(a) No, this is not a systematic sample. A systematic sample requires choosing a random starting point and then selecting members at regular intervals from an ordered list. Selecting members whose number ends in 000 does not involve a random start, and the interval depends on how membership numbers are assigned. It is closer to opportunity sampling based on a convenient criterion.'),p('(b) The gym could use a genuine systematic sample: order all members by membership number, calculate a sampling interval $k$, choose a random starting point, and then select every $k$th member. Alternatively, using a random number generator to select members would produce a simple random sample, which is free from bias.')]),
 example([...samplingQuestions[2],p('Similarities: Both methods divide the population into groups (strata or quotas) and ensure that the sample reflects the structure of the population by taking a proportional number from each group.'),p('Differences: In stratified random sampling, members within each stratum are selected randomly using a sampling frame, making the process free from selection bias. In quota sampling, the interviewer fills each quota by choosing people who fit the criteria — the selection within each group is not random, which can introduce bias. Quota sampling does not require a sampling frame, whereas stratified sampling does. Non-responses are not recorded in quota sampling (the interviewer simply moves on), whereas in stratified sampling, non-responses can be tracked.')]),
 example([...samplingQuestions[3],p('(a) The mean of the sample:'),m(raw`\bar{x}=\frac{4+7+6+8+2}{5}=\frac{27}{5}=5.4\text{ hours per week}`),p('(b) The researcher used opportunity sampling, selecting the first 5 people available at a specific time and place. The data is unlikely to be reliable because the sample is very small (only 5 people) and is collected at only one location and one time. People entering a supermarket on a Monday morning may not be representative of the town as a whole — for example, workers and students would be excluded.'),p('(c) Improvement 1: Take a much larger sample to improve the accuracy and reliability of the estimate.'),p('Improvement 2: Collect data at different locations and at different times of day and days of the week to obtain a more representative cross-section of the town’s population.')]),
 ]),
]),
lesson('1.3 Types of Data',[
 p('When collecting data, it is important to classify the type of variable being measured. The classification determines which statistical techniques and diagrams are appropriate for analysis.'),
 group('Classification of Variables',[
 p('Quantitative data — associated with numerical observations. Examples: height, mass, number of children.'),p('A continuous variable can take any value in a given range. Example: time can be 2.1 s, 2.01 s, etc.'),p('A discrete variable can take only specific values in a given range. Example: the number of girls in a family.'),p('Qualitative data — associated with non-numerical observations. Examples: hair colour, type of car.'),p('Grouped data — when data is presented in a grouped frequency table, the specific values are not shown. The groups are called classes.'),p('Class boundaries are the maximum and minimum values in each class. The midpoint is the average of the class boundaries. The class width is the difference between the upper and lower class boundaries.'),
 ]),p('When data values are measured to a given degree of accuracy (e.g. to the nearest mm), the class boundaries may differ from the values shown in the table. For example, if lengths are recorded to the nearest mm and a class is written as 30–31, the true class boundaries are 29.5 and 31.5.'),
 group('Worked Example 6',[
 p('The lengths, $x$ mm, to the nearest mm, of the forewings of a random sample of male adult butterflies are measured and shown in the table.'),table(['Length of forewing (mm)','Number of butterflies, $f$'],[['30–31','2'],['32–33','25'],['34–36','30'],['37–39','13']]),p('(a) State whether length is (i) quantitative or qualitative, (ii) discrete or continuous.'),p('(b) Write down the class boundaries, midpoint and class width for the class 34–36.'),p('(a) (i) Length is quantitative because it is a numerical measurement.'),p('(ii) Length is continuous because it can take any value within a range (a forewing could be 34.7 mm, for instance).'),p('(b) Since the data are recorded to the nearest mm, the true class boundaries for the class 34–36 are:'),p('Lower class boundary = 33.5 mm, Upper class boundary = 36.5 mm.'),m(raw`\text{Midpoint}=\frac{33.5+36.5}{2}=35\ \mathrm{mm}.`),m(raw`\text{Class width}=36.5-33.5=3\ \mathrm{mm}.`),
 ]),group('Practice Questions',[
 typeQuestions[0],typeQuestions[1],typeQuestions[2],table(['Mass, $m$ (kg)','Frequency'],[[raw`$1.2\le m<1.3$`,'8'],[raw`$1.3\le m<1.4$`,'28'],[raw`$1.4\le m<1.5$`,'32'],[raw`$1.5\le m<1.6$`,'22']]),...massParts,
 ]),group('Practice Solutions',[
 example([typeQuestions[0],p('(a) Quantitative — height is a numerical measurement.'),p('(b) Qualitative — colour is a non-numerical description.'),p('(c) Quantitative — time is a numerical measurement.'),p('(d) Quantitative — shoe size is a numerical value.'),p('(e) Qualitative — names are non-numerical descriptions.')]),
 example([typeQuestions[1],p('(a) Discrete — shoe sizes take only specific values (e.g. 5, 5.5, 6, …).'),p('(b) Continuous — length can take any value within a range.'),p('(c) Discrete — the number of people must be a whole number.'),p('(d) Continuous — weight can take any value within a range.'),p('(e) Continuous — time can take any value within a range.')]),
 example([typeQuestions[2],...massParts,p(raw`(a) The third group is $1.4\le m<1.5$. Since the class boundaries are given using inequalities, the values in the table are the actual class boundaries:`),p('Lower class boundary = 1.4 kg, Upper class boundary = 1.5 kg.'),p(raw`(b) The second group is $1.3\le m<1.4$.`),m(raw`\text{Midpoint}=\frac{1.3+1.4}{2}=1.35\ \mathrm{kg}`),p(raw`(c) The first group is $1.2\le m<1.3$.`),m(raw`\text{Class width}=1.3-1.2=0.1\ \mathrm{kg}`)]),
 ]),
]),
lesson('1.4 The Large Data Set',[
 p('In the Edexcel AS and A-Level examinations, you are expected to be familiar with the large data set provided by Edexcel. Questions on the large data set test your knowledge of the data itself, the variables recorded, the weather stations included, and how to handle and interpret real-world data.'),
 group('Key Facts About the Large Data Set',[
 p('The data set consists of weather data samples provided by the Met Office for five UK weather stations and three overseas weather stations, over two time periods: May to October 1987 and May to October 2015.'),p('UK Stations: Camborne, Heathrow, Hurn, Leeming, Leuchars.'),p('Overseas Stations: Beijing (China), Jacksonville (USA), Perth (Australia).'),p(raw`Variables recorded: Daily mean temperature ($^\circ\mathrm{C}$), daily total rainfall (mm), daily total sunshine (hours), daily mean wind direction and windspeed (knots), daily maximum gust (knots), daily maximum relative humidity (%), daily mean pressure (hPa), daily mean cloud cover (oktas).`),p('Important notes:'),p('Overseas stations record only: daily mean temperature, daily total rainfall, daily mean pressure and daily mean windspeed.'),p('Rainfall amounts less than 0.05 mm are recorded as “tr” (trace). A value of “n/a” or a blank means data is not available. Cloud cover is measured in oktas (0 = clear sky, 8 = completely overcast). Wind direction is given in compass bearings and cardinal directions. The Beaufort scale categorises windspeed.'),
 ]),p('When working with the large data set, you need to be aware that data may need cleaning before calculations can be performed. This means replacing or removing non-numerical entries such as “tr” and “n/a”. You also need to recognise which variables are qualitative (e.g. wind direction as a compass point) and which are quantitative.'),
 group('Worked Example 7',[
 p('Joshua is investigating the daily total rainfall in Hurn for May to October 2015. He wishes to calculate the mean daily total rainfall.'),p('(a) Explain why Joshua needs to clean the data before calculating the mean.'),p('(b) Suggest how Joshua should deal with “tr” values when cleaning the data.'),p('(a) The data needs to be cleaned because some entries are recorded as “tr” (trace), which represents rainfall amounts less than 0.05 mm. These are non-numerical entries and cannot be included directly in a calculation of the mean.'),p('(b) Joshua could replace each “tr” value with 0 (since trace amounts are negligibly small) or with 0.025 (the midpoint of the range 0 to 0.05). Replacing with 0 is the most common approach and will have minimal effect on the calculated mean.'),
 ]),group('Worked Example 8',[
 p(raw`Keith is studying the variable Daily Mean Wind Direction, in degrees, from the large data set. He summarised the data for Camborne from 1987 into 4 compass directions: North ($316^\circ$–$45^\circ$), East ($46^\circ$–$135^\circ$), South ($136^\circ$–$225^\circ$) and West ($226^\circ$–$315^\circ$).`),p('(a) Is Daily Mean Wind Direction a qualitative or quantitative variable? Explain your answer.'),p('(b) Explain whether it is appropriate to use the mean to summarise wind direction data.'),p('(a) Daily Mean Wind Direction measured in degrees is a quantitative variable because it takes numerical values. However, when wind direction is recorded as compass categories (N, S, E, W), it becomes a qualitative variable.'),p(raw`(b) It is generally not appropriate to use the mean to summarise wind direction data. Wind direction is a circular variable — for example, the mean of $350^\circ$ and $10^\circ$ is not $180^\circ$ (due south), but should be close to $0^\circ/360^\circ$ (due north). Standard arithmetic mean does not account for this circular nature. The mode (most common direction) or a circular mean would be more appropriate measures.`),
 ]),group('Practice Questions',dataQuestions),group('Practice Solutions',[
 example([dataQuestions[0],p(raw`(a) Quantitative — temperature is measured numerically in $^\circ\mathrm{C}$.`),p('(b) Qualitative — when recorded as a compass direction (N, NE, E, etc.) it is a category, not a number.'),p('(c) Quantitative — rainfall is measured numerically in mm.'),p('(d) Quantitative — cloud cover is measured numerically on a scale from 0 to 8 oktas. (It is discrete since it can only take integer values 0, 1, 2, …, 8.)')]),
 example([dataQuestions[1],p('The two time periods allow comparisons to be made over time. Students can investigate whether weather patterns have changed between 1987 and 2015, which could provide evidence for or against climate change. Having two time periods also allows students to consider seasonal patterns and whether trends are consistent across different decades.')]),
 example([dataQuestions[2],p('The student may encounter missing data (recorded as “n/a” or blank entries) or non-numerical entries. Before calculating the standard deviation, the student needs to clean the data by removing or replacing any non-numerical entries. The affected values should be excluded from the calculation, and the sample size $n$ should be adjusted accordingly to reflect only the valid data points used.')]),
 example([dataQuestions[3],p('Recorded for all eight stations: Daily mean temperature and daily total rainfall. (Also daily mean pressure and daily mean windspeed.)'),p('Recorded only for UK stations: Daily total sunshine and daily maximum relative humidity. (Also daily maximum gust, daily mean cloud cover and daily mean wind direction.)')]),
 ]),
]),
];
